version: '3.1'
services:
#  db:
#    image: mongo
#    container_name: mongo
#    restart: always
#    volumes:
#      - ./data/db:/data/db
#    ports:
#      - 27017:27017
#    env_file:
#      - .env
#    networks:
#      - generated_default
  web:
    container_name: btcpal_register
    build: .
    external_links:
      - mongod:db
    restart: unless-stopped
    networks:
    - generated_default
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  generated_default:
    external:
      name: generated_default
