version: '3.1'
services:
  web:
    container_name: webapp
    build: .
    links:
      - "db:db"
    depends_on:
    - db
    restart: unless-stopped
    networks:
    - generated_default
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  generated_default:
    external:
      name: generated_default
