version: '3.1'

services:

  web:
    build: .
    restart: unless-stopped
    environment:
    - NODE_ENV=development
    links:
    - mongo
    ports:
    - 5555:5555
    depends_on:
    - mongo
    - mongo-express
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - ./data/db:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
