version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
    - ./data/db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null

  web:
    build: .
    restart: unless-stopped
    environment:
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      NODE_ENV: development
      MONGO_CONTAINER_NAME: mongodb
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      GMAIL_PASS: ${GMAIL_PASS}
      GMAIL_USER: ${GMAIL_USER}
      # Links allow you to define extra aliases
    links:
    - "mongodb:mongo"
    ports:
    - 5555:5555
    depends_on:
    - mongodb
#
#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    depends_on:
#      - mongodb
#    links:
#      - mongodb
#    ports:
#    - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: user
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
